# Generated by Django 5.2.1 on 2026-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsal',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
    ]
