# Generated by Django 5.2.1 on 2026-01-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_alter_timeslot_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('in_queue', 'In Queue')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(),
        ),
    ]
