# Generated by Django 5.2.1 on 2026-01-02 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0004_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalimage',
            name='futsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futsal_image', to='futsal.futsal'),
        ),
    ]
