# Generated by Django 5.2.1 on 2026-01-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0005_alter_futsalimage_futsal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day_of_week', 'start_time', 'end_time']},
        ),
    ]
