# Generated by Django 5.2.1 on 2026-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0006_alter_timeslot_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='booking_id',
        ),
        migrations.AlterField(
            model_name='futsal',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
