# Generated by Django 5.2.1 on 2026-01-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0007_remove_timeslot_booked_by_remove_timeslot_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsal',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
