# Generated by Django 5.2.1 on 2026-01-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0008_alter_futsal_latitude_alter_futsal_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='map_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
