# Generated by Django 5.2.1 on 2026-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0009_futsal_map_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decision_mail_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='request_mail_status',
            field=models.BooleanField(default=False),
        ),
    ]
