# Generated by Django 5.2.1 on 2026-01-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0010_booking_decision_mail_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='phone',
            field=models.CharField(default='#####', max_length=50),
            preserve_default=False,
        ),
    ]
