# Generated by Django 5.2.1 on 2026-02-04 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0011_futsal_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsal',
            name='price_per_hour',
        ),
        migrations.CreateModel(
            name='FutsalPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('day', models.CharField(choices=[('weekday', 'Weekdays (Sun–Fri)'), ('sat', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='futsal.futsal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FutsalPricingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('weekday_open', models.TimeField()),
                ('weekday_close', models.TimeField()),
                ('off_start', models.TimeField()),
                ('off_end', models.TimeField()),
                ('peak_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('off_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('saturday_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('futsal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_config', to='futsal.futsal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
