# Generated by Django 5.2.1 on 2026-02-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='d', max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
